### ISSUE TITLE
a more authoritative data source

### ISSUE THREAD

**Issue by lizelive** [zbrox/iso_currency#12]
goto <https://www.iso.org/iso-4217-currency-codes.html>
click on [ISO 4217 CODES IN XLS AND XML FORM](https://www.six-group.com/en/products-services/financial-information/data-standards.html)
download <https://www.six-group.com/dam/download/financial-information/data-center/iso-currrency/lists/list_one.xml>

**Comment by zbrox** [comment]
Hey, thanks for the report. Currently the data is not refreshed very often (and I mean both the source data itself - the ISO standard and the data included in the crate). The ISO DB is missing some of the datapoints that are used by the crate. Having that in mind I don't see a reason to change the data source. It will require reformatting to the structure of the [data file](https://github.com/zbrox/iso_currency/blob/master/isodata.tsv) used now and then extra work to include the missing data points without adding any value just extra work.

However if you notice a mistake in the data where it is not matching the latest official ISO 4217 standard or the additional data points (e.g. currency symbols) please file an issue or even a pull request. Any help is welcome.
