### ISSUE TITLE
Subunits fraction are not always correct

### ISSUE THREAD

**Issue by b4D8** [zbrox/iso_currency#15]
Hi there,

Thanks for your work on this crate!

## Problem

[ISO official data](https://www.six-group.com/dam/download/financial-information/data-center/iso-currrency/lists/list-one.xls) provides the number of minor units for most of the listed currencies which is actually an `exponent` because all listed currencies are base 10 for both their major and minor unit.

The `subunits_fraction` should then be be the result of 10 ^ `exponent` but this is not currently the case for 19 currencies (taking aside the 2 special cases detailed below).

<details>

|alpha2|current|actual  |
|------|---|-----|
|BIF   |100|1    |
|CLF   |100|10000|
|CLP   |100|1    |
|DJF   |100|1    |
|GNF   |100|1    |
|ISK   |100|1    |
|JOD   |100|1000 |
|JPY   |100|1    |
|KMF   |100|1    |
|KRW   |100|1    |
|MGA   |5  |100  |
|MRU   |5  |100  |
|PYG   |100|1    |
|RWF   |100|1    |
|UGX   |100|1    |
|UYI   |100|1    |
|UYW   |100|10000|
|VND   |10 |1    |
|XAF   |100|1    |
|XOF   |100|1    |
|XPF   |100|1    |

</details>

## Edge case

[Malagasy ariary](https://en.wikipedia.org/wiki/Malagasy_ariary) (`MRU`) and the [Mauritanian ouguiya](https://en.wikipedia.org/wiki/Mauritanian_ouguiya) (`MGA`) are technically divided into 5 subunits. If they have a face value of "1/5", these are not used in practice. When written out, a single significant digit is used (example: 1.2 UM so that 10 UM = 1 MRU). -- Source [Wikipedia](https://en.wikipedia.org/wiki/ISO_4217#cite_note-divby5-15).

While those are currently registered by the crate as having 5 `subunits_fraction`, IMHO I believe they should be updated to match ISO definition and actual usage (which is a breaking change).

## Solution

- update the internal dataset with `exponent` instead of `subunits_fraction`
- add `exponent()` getter function
- update `subunits_fraction()` to return the result of `10_u16.pow(minor_units)`

PR on the way :rocket:

**Comment by zbrox** [comment]
You are absolutely correct. Thank you for the detailed explanation and work put in. I will check out the pull request in a minute.

**Comment by zbrox** [comment]
Your pull request is merged. I will try to release 0.5.0 today.
