### ISSUE TITLE
Proposal: get Currency from Country

### ISSUE THREAD

**Issue by b4D8** [zbrox/iso_currency#19]
A nice addition would be to be have the inverse of `used_by()`, something like:

```rust
/// Returns a vector of the currencies a country is known to use
fn from_country(country: Country) -> Option<Vec<Currency>> {}

/// Constructor for Currency based on a best guess from a Country
fn guess_from_country(country: Country) -> Option<Self> {}
```

The later is kind of like ICU [likely subtags](https://www.unicode.org/cldr/cldr-aux/charts/25/supplemental/likely_subtags.html) but would require to rework on the data.

**Comment by zbrox** [comment]
Yeah, that is a good idea, it should have the inverse of `used_by()`. `from_country` seems straightforward enough.

What is your idea about reworking the source data to be able to implement `guess_from_country`? Also wondering now, how many countries use more than one currency and do we have the data (without extra input, just the country itself) to decide which is the likely currency used in those cases?

**Comment by b4D8** [comment]
Thanks for merging the PR and your being so reactive about this.

I had a deeper look into it. This is the current state of the internal dataset:

- 181 unique currencies
- 248 unique countries
- 14 currencies without country: `NAD`, `XAG`, `XAU`, `XBA`, `XBB`, `XBC`, `XBD`, `XDR`, `XPD`, `XPT`, `XSU`, `XTS`, `XUA` and `XXX`. All of them seem to be funds/specials except for theNamibian dollar `NAD`which looks like a missing mapping to `NA` (probably stripped during data sanitation)
- 17 currencies with more than 1 country: `ANG`,  `AUD`, `CHF`, `DKK`, `EUR`, `GBP`, `ILS`, `INR`, `MAD`, `NOK`, `NZD`, `USD`, `XAF`, `XCD`, `XOF`, `XPF` and `ZAR`
- 19 countries with more than 1 currency: `BO`, `CH`, `CL`, `CO`, `CU`, `MX`, `SL`, `UY` and `VE`
     - and those currencies are: `BOB`, `BOV`, `CHE`, `CHW`, `CLF`, `CLP`, `COP`, `COU`, `CUC`, `CUP`, `MXN`, `MXV`, `SLE`, `SLL`, `UYI`, `UYU`, `UYW`, `VED` and `VES`

Those last one are the one to tackle if we want to provide the "best guess".
Looking at them, it shouldn't be that hard as a human to decide but for the function would require to rework on the data.

A possible option would be to add a new `flags` column that accepts a semicolon separated list of flags (which we could easily extended if required in the future) among: `fund`, `superseded` etc. 

Those flags could also have their own column with a bool.

**Comment by b4D8** [comment]
Following up on this "flags" idea, we would have:

-  `special`: `XDR`, `XSU`, `XUA`, `XBA`, `XBB`, `XBC`,  `XBD`, `XTS`, `XXX`, `XAU`, `XPD`, `XPT`, `XAG` (this is exhaustive from official "list-one"). Although they are always prefixed with `X` it doesn't discriminate (`XAF` and `XOF` are "real" currencies).
- `fund`: `BOV`, `CLF`, `COU`, `MXV`, `CHW`, `CHE`, `USN`, `UYI` and `UYW` (this is exhaustive from official "list-two")
- `superseded`: `VED` (in favor of `VES` since [2018](https://en.wikipedia.org/wiki/Venezuelan_bol%C3%ADvar#Sovereign_bol%C3%ADvar)), `CUC` (in favor of `CUP` since [2020](https://en.wikipedia.org/wiki/Cuban_peso)), `SLL` (in favor or `SLE` since [2022](https://en.wikipedia.org/wiki/Sierra_Leonean_leone)) (this is from on my own research)
- `deprecated`: this flag could be reserved for currencies of the "list-three" but supporting it is probably overkill and would require to rework on the data because some code get recycled

Then the 19 countries with more than 1 currency mentioned before correctly resolve to 1currency  that is neither special, a fund nor superseded.

**Comment by zbrox** [comment]
Ok, when you said "rework" of the data I imagined you mean some complete restructuring but adding one more column would not be a big hassle. It would be nice to have some metadata like `deprecated` and others you describe. And from your research it seems it should be a huge amount of effort to manually edit in the data in the tsv.

How do you see the serialization of those flags? An extra flag function on the `Currency` enum returning some `Flags` struct or something else?

**Comment by zbrox** [comment]
> Hi @zbrox, sorry I couldn't get back at you sooner. Yes this is exactly the implementation I was thinking about. For convenience, we could include a set of related functions:
> 
> * `flag() -> Option<Flag>`
> * `has_flag(flag: Flag) -> bool`
> * `is_fund() -> bool`
> * `is_superseded() -> bool`
> * `is_special() -> bool`
> * `latest() -> Self` which would return the Currency itself or its replacement if superseded
> * `from_country(country: Country) -> Option<Vec<Self>>`
> * `impl From<Country> for Currency {}` which would return the only unflagged Currency associated with the Country

Sounds good. We can probably start with the simpler flags like if it's a fund or a special currency.

**Comment by zbrox** [comment]
Hey @b4D8 I started implementing your ideas here #26 

I'd appreciated it if you take a look when you have time and tell me what you think or even make changes yourself if you can. So far I've implemented almost all of the suggested interface except the last 2 functions related converting from a `Country`. The last thing remaining is to write the function documentations.

On a side note, I'm still not sure about using the word "flag" when countries and currencies are involved :)
