### ISSUE TITLE
Proposal: get Country from Currency

### ISSUE THREAD

**Issue by b4D8** [zbrox/iso_currency#21]
From the data exploration in #19, I figured could easily further provide:

```rust
/// Returns a vector of the countries a currency is known to be used in
fn countries(&self) -> Option<Vec<Country>> {}

/// Return a single Country based on a best guess
fn guess_country(&self) -> Option<Vec<Country>> {}
```

For the later, we only have to handle the 19 currencies with more than 1 country.

In my opinion, 13 of them actually resolve quite naturally:
- `AUD` -> Australia
- `CHF` -> Switzerland
- `DKK` -> Denmark
- `GBP` -> UK
- `ILS` -> Israel
- `INR` -> India
- `MAD` -> Morocco
- `NOK` -> Norway
- `NZD` -> New Zealand
- `USD` -> USA
- `ZAR` -> South Africa

The 6 remaining (`ANG`, `EUR`, `XAF`, `XCD`, `XOF` and `XPF`) do require an opinionated guess which could be solved by returning `None` or the first Country in logical order.

We could also suggest that [iso_country](https://github.com/pzol/iso_country) provide reciprocal  `from_currency` and `from_currency_guess` impl on `Country`.

**Comment by zbrox** [comment]
Without some extra data point would be hard to guess, especially for such currencies like the EUR. I wouldn't wanna take it up to decide what is the "default" Euro country :) I'm just wondering if there's any value added to such guesses and how to instruct users of the library what function is more useful in what use cases. 

Do you have some specific use case about this so I can imagine this better?

On another note [iso_country](https://github.com/pzol/iso_country) is unfortunately not maintained now. I have an open pull request without a response for maybe 2 years now. So I guess the maintainer has no time for it.

**Comment by b4D8** [comment]
Actually, I don't have any use case for this and it is probably not a great idea... I guess I just wanted to see how far we could go with the dataset. I think you should close this.
