### ISSUE TITLE
Request: `impl From<String> for Currency`

### ISSUE THREAD

**Issue by Uzaaft** [zbrox/iso_currency#33]
Currently, using the Currency enum with sqlx won't work due to it not implementing `From<String>`. I save the currency codes as a string for ease. 

I use `pub struct Currency(iso_currency::Currency)` inside my codebases to work around this problem, but it would be nice if we can add an implementation into this library.

I currently do:
```rust
pub struct Currency(iso_currency::Currency)

impl From<String> for Currency {
    fn from(value: String) -> Self {
        let iso_currency = iso_currency::Currency::from_str(&value).unwrap();
        Self(iso_currency)
    }
}
```

Which works fine for me, but that unwrap might not be what one would like inside a library. If my implementation is good enough, I can open a PR.  What do you think? Would you be open to add `From<String>` for currency into the library?

**Comment by zbrox** [comment]
Hey, first of all sorry for the delayed reply. 

I think it will be great if there's support for sqlx, I use it as well. However, as you've noted having just an unwrap in a From<String> implementation is probably not ideal. Unfortunately, as far as I remember sqlx doesn't support using a TryFrom implementation instead. 

If we wanna do it properly I guess we need to implement (behind a series of features for each type of database) support for sqlx's Decode and Type traits.

I will not have time this week but in a couple of weeks after I first take the plunge and merge #31 (probably in the upcoming days). If you'd like to take a stab at implementing this yourself, just give me a couple of days before I merge the refactor, so to avoid the pain of having to solve merge conflicts.

**Comment by zbrox** [comment]
Hey, @Uzaaft, do you wanna try #34 and see if it is useful?

**Comment by Uzaaft** [comment]
@zbrox  I'll test it over the weekend 🫡

**Comment by Uzaaft** [comment]
> Hey, @Uzaaft, do you wanna try #34 and see if it is useful?

Muy useful signore.
