### ISSUE TITLE
Use iso_country in Currency::used_by

### ISSUE THREAD

**Issue by IcanDivideBy0** [zbrox/iso_currency#7]
This might be more handy to use [iso_countries](https://crates.io/crates/iso_country) instead of plain old str for `Currency::used_by`, this way we can also add a function to get currencies used by a specific country ?

**Comment by zbrox** [comment]
Sounds good. I will look into it.

**Comment by zbrox** [comment]
I created a feature branch with the initial replacement of strings with the Country enum from iso_countries. There are only a couple of issues so I'm a bit unsure how to continue.

1) Some of the entities that were represented by strings are super national ones like say the International Monetary Fund. I guess those can be skipped, cause maybe for practical purposes they are not needed if they're not real places one can visit.

2) The information in the iso_countries crate has not been updated in quite a while so some entities are either missing (e.g. Eswathini) or not updated to new names (e.g. North Macedonia).

**Comment by IcanDivideBy0** [comment]
After digging a bit on crates.io, I'm not sure if this is a good idea anymore
* https://crates.io/crates/isocountry does not seems up to date either
* https://crates.io/crates/jurisdiction seems up to date (contains Eswatini at least which is pretty recent) but I'm not sure how much I trust this one on the long run: repository is not public, home page leads to a company frontpage ...

both missing

**Comment by IcanDivideBy0** [comment]
Ok, I've sent a 1.0 release request to `iso_country` https://github.com/pzol/iso_country/issues/7

from the feature/iso_countries branch:
* I think countries that are not part of the ISO-3166 can be removed without major downsides for the quality of the curent crate
* even tho Swaziland was renamed Eswatini, the ISO code didn't changed and is still `SZ` `SWZ`, so this one can be used
* from [wikipedia](https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes) Caribbean Netherlands should use the `BQ` `BES` code

With all that done, all problematic cases should be resolved. Any more thought on that?

**Comment by zbrox** [comment]
Yeah, the author of `iso_country` has already merged my pull request for updating the data. But I did only the part which last night I could automate by scraping the wikipedia article. The data in `lib.rs` where the actual enum is still needs an update. If I have time today I can play a bit to try to automate that from the `data.rs` with a build script. 

But yeah, if this is updated I can finish the remaining cases that are now breaking on the feature branch and release a 0.3.0.

**Comment by zbrox** [comment]
Looking at it there's some data duplication so I'll try to refactor it to read csv data (which is easily downloaded from Wikipedia) and do some codegen on the necessary structures. I will probably not have time to finish today since it's quite a full day. Looking at it this is probably also a better approach for `iso_currency` as well cause it will make updating the data or correcting it much easier.

**Comment by zbrox** [comment]
This is the pull request: https://github.com/pzol/iso_country/pull/8

**Comment by zbrox** [comment]
The merging of the pull request doesn't change much about this crate. I've pushed the feature addressing this. Gonna release `0.3.0` in a second.

**Comment by zbrox** [comment]
Forgot to update the documentation about using `iso_country` so I released another version - 0.3.1.
